function addnumbers(){
    let x = 10
    let y = 15
    let numbers = x + y
    console.log("x and y is", numbers);}

    function addnumbers(){
        let x = 20
        let y = 25
        let numbers = x + y
        console.log("x and y is", numbers);}
       

        
        function addnumbers(){
            let x = 30
            let y = 35
            let numbers = x + y
            console.log("x and y is", numbers);}
                
        
        